Repository aakvatech/HMS_TZ, pull requests merged in 2023-02, with the labels that each got.

#338 feat: check if patient readmitted again before clearing the inpatient record number from patient
  hms_tz/hms_tz/doctype/inpatient_record/inpatient_record.py
Labels: version-13-hotfix, version-14-hotfix

#341 fix: stop creation of patient if cardno already used by another patient
  hms_tz/nhif/api/patient.js
  hms_tz/nhif/api/patient.py
Labels: version-13-hotfix, version-14-hotfix

#344 feat: alert receptionists if patient has multiple appointments
  hms_tz/nhif/api/patient_appointment.py
Labels: version-13-hotfix, version-14-hotfix

#349 fix: typeError cannot concatenate str and nontype, it was happend when card no is not found
  hms_tz/nhif/api/patient.py
Labels: version-13-hotfix, version-14-hotfix

#352 feat: adjust clinical notes to replace/remove claim file
  hms_tz/nhif/doctype/nhif_patient_claim/nhif_patient_claim.py
Labels: version-13-hotfix, version-14-hotfix

#357 feat: add multiple practitioner number in json if multiple claims merged together
  hms_tz/nhif/doctype/nhif_patient_claim/nhif_patient_claim.py
Labels: version-13-hotfix, version-14-hotfix, conflict

#360 fix: conflicts
  hms_tz/nhif/doctype/nhif_patient_claim/nhif_patient_claim.py
Labels: version-13-hotfix, version-14-hotfix

#363 chore: add full name of the practitioner on clinical notes to distinguish who wrote notes
  hms_tz/nhif/doctype/nhif_patient_claim/nhif_patient_claim.py
Labels: version-13-hotfix, version-14-hotfix

#366 v3.1.0
  .mergify.yml
  hms_tz/__init__.py
  hms_tz/hms_tz/doctype/inpatient_record/inpatient_record.py
  hms_tz/hms_tz/doctype/patient_appointment/patient_appointment.js
  hms_tz/hooks.py
  hms_tz/nhif/api/healthcare_utils.py
  hms_tz/nhif/api/patient.js
  hms_tz/nhif/api/patient.py
  hms_tz/nhif/api/patient_appointment.py
  hms_tz/nhif/api/patient_encounter.py
  hms_tz/nhif/doctype/company_nhif_settings/company_nhif_settings.js
  hms_tz/nhif/doctype/company_nhif_settings/company_nhif_settings.json
  hms_tz/nhif/doctype/nhif_patient_claim/nhif_patient_claim.js
  hms_tz/nhif/doctype/nhif_patient_claim/nhif_patient_claim.json
  hms_tz/nhif/doctype/nhif_patient_claim/nhif_patient_claim.py
  hms_tz/patches.txt
  hms_tz/patches/custom_fields/company_field_on_healthcare_practitioner.py
  hms_tz/patches/property_setter/property_setter_for_department_field_on_patient_appointment.py
Labels: conflict
